name: wec-decider
channels:
  - conda-forge
  - nrel
dependencies: 
  - python
  - pandas
  - numpy 
  - numpy-financial # econ module
  - scipy 
  - matplotlib 
  - h5pyd
  - requests
  - wecopttool  # dynamics module
  - nrel-pysam  # econ module
  - pyxdsm      # diagram generation
  - openmdao
  - gdown       # data for CEM module
  - ipykernel   # jupyter
  - pip
  - catalystcoop.pudl <= 2022.11.30, >= 0.6.0 # for powergenome (otherwise too new python version [3.11] is installed)
  - pydantic[email] >= 1.7, <2 # for pudl 2022.11.30
  - pyarrow = 7
  - nbconvert # used by calkit
  - pyogrio
#  - mpi4py 
#  - petsc4py
  - ipywidgets # for development (Jupyter notebook widgets)
  - pip:
  # - calkit-python
    - mhkit
    - powergenome@git+https://github.com/rebeccamccabe/PowerGenome/@fix-int-cap-recovery-period
    - gridstatus
    - wecopttool[geometry]
    - omxdsm@https://github.com/onodip/OpenMDAO-XDSM/tarball/master
#    - GenX
#    - pygenx
